site_name: Dj Waanverse Auth.
site_url: https://dj-waanverse-auth.waanverse.com/

nav:
    - Home: index.md
    - Installation Guide: installation.md
    - Configuration Settings: configuration.md
    - API Overview: endpoints.md
    - API Endpoints:
          - User Login: endpoints/login.md
          - Verify Email: endpoints/verify_email.md
          - Confirm Password Reset: endpoints/confirm_reset_password.md
          - User Logout: endpoints/logout.md
          - Refresh Token: endpoints/refresh_token.md
          - Resend Verification Email: endpoints/resend_verification_email.md
          - Reset Password: endpoints/reset_password.md
          - User Signup: endpoints/signup.md
          - User Info: endpoints/userinfo.md
          - Multi-Factor Authentication (MFA):
                - Deactivate MFA: endpoints/mfa/deactivate.md
                - Enable MFA: endpoints/mfa/enable.md
                - Generate MFA Recovery Codes: endpoints/mfa/generate_code.md
                - MFA Login: endpoints/mfa/login.md
                - MFA Status: endpoints/mfa/status.md
                - Verify MFA: endpoints/mfa/verify.md

theme:
    name: material
    custom_dir: docs/overrides
    logo: assets/images/logo.png
    favicon: assets/images/favicon.ico
    features:
        - navigation.instant
        - navigation.instant.prefetch
        - navigation.instant.progress
        - navigation.sections
        - navigation.top
        - search.suggest
        - search.highlight
        - content.tabs.link
        - content.code.copy
        - navigation.tracking
        - navigation.path
        - navigation.footer

    language: en
    palette:
        - scheme: default
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
          primary: teal
          accent: teal
        - scheme: slate
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
          primary: teal
          accent: teal

extra:
    consent:
        title: Cookie consent
        description: >-
            We use cookies to recognize your repeated visits and preferences, as well
            as to measure the effectiveness of our documentation and whether users
            find what they're searching for, With your consent, you're helping us to
            make our documentation better.
        actions:
            - accept
            - reject

    analytics:
        provider: google
        property: G-CP8WX06TVQ

    version:
        provider: mike
        default: stable
        alias: true
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/waanverse
    generator: false

plugins:
    - privacy
    - search
    - social

copyright: Copyright &copy; 2024 All rights reserved. Waanverse Labs Inc. –
    <a href="#__consent">Change cookie settings</a>

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - toc:
          permalink: True
