name: ci
on:
    push:
        branches:
            - master
            - main
permissions:
    contents: write
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Configure Git Credentials
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

            - uses: actions/setup-python@v5
              with:
                  python-version: 3.12.1

            - name: Cache Dependencies
              uses: actions/cache@v4
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
                  restore-keys: |
                      ${{ runner.os }}-pip-

            - name: Install Dependencies
              run: pip install -r requirements.txt

            - name: Clone gh-pages Branch
              run: |
                  git fetch origin gh-pages --depth=1

            - name: Deploy Documentation
              run: mike deploy --push --update-aliases 0.0a1

            - name: Set Default Documentation Version
              run: mike set-default --push latest
