name: ci
on:
    push:
        branches:
            - master
            - main
permissions:
    contents: write
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            
            - name: Configure Git Credentials
              run: |
                  git config user.name github-actions[bot]
                  git config user.email 41898282+github-actions[bot]@users.noreply.github.com
                  
            - uses: actions/setup-python@v5
              with:
                  python-version: 3.12.1
            
            - name: Cache Dependencies
              uses: actions/cache@v4
              with:
                  key: mkdocs-material-${{ hashFiles('requirements.txt') }}
                  path: ~/.cache/pip
                  restore-keys: |
                      mkdocs-material-
            
            - name: Install Dependencies
              run: pip install -r requirements.txt
              
            - name: Deploy Documentation
              run: mike deploy --push --update-aliases 0.0a1 latest
              
            - name: Set Default Documentation Version
              run: mike set-default latest
